filepath: ""
namespace: jx-staging
repositories:
- name: dev
  url: http://192.168.49.2.nip.io/bucketrepo
releases:
- chart: dev/jx3-project-python-01-2
  version: 0.0.1
  name: jx3-project-python-01-2
templates: {}
renderedvalues: {}
