apiVersion: v1
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - rocannon77/jx3-minikube-01
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - rocannon77/jx2-python-http-01-6
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - rocannon77/jx3-project-python-01-2
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - rocannon77/jx3-project-python-01-3
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - rocannon77/jx3-python-01-4
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - rocannon77/jx3-python-http-01-5
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - rocannon77/jx3-python-http-01-7
      require_self_approval: true
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
      maps:
        env/prow/job.yaml:
          name: config
        env/prow/plugins.yaml:
          name: plugins
    external_plugins:
      rocannon77/jx2-python-http-01-6:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      rocannon77/jx3-minikube-01:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      rocannon77/jx3-project-python-01-2:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      rocannon77/jx3-project-python-01-3:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      rocannon77/jx3-python-01-4:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      rocannon77/jx3-python-http-01-5:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      rocannon77/jx3-python-http-01-7:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
    heart: {}
    label:
      additional_labels: null
    owners: {}
    plugins:
      rocannon77/jx2-python-http-01-6:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      rocannon77/jx3-minikube-01:
      - config-updater
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      rocannon77/jx3-project-python-01-2:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      rocannon77/jx3-project-python-01-3:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      rocannon77/jx3-python-01-4:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      rocannon77/jx3-python-http-01-5:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      rocannon77/jx3-python-http-01-7:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
    requiresig: {}
    sigmention: {}
    size:
      l: 0
      m: 0
      s: 0
      xl: 0
      xxl: 0
    triggers:
    - repos:
      - rocannon77/jx3-minikube-01
      trusted_org: todo
    - repos:
      - rocannon77/jx2-python-http-01-6
      trusted_org: todo
    - repos:
      - rocannon77/jx3-project-python-01-2
      trusted_org: todo
    - repos:
      - rocannon77/jx3-project-python-01-3
      trusted_org: todo
    - repos:
      - rocannon77/jx3-python-01-4
      trusted_org: todo
    - repos:
      - rocannon77/jx3-python-http-01-5
      trusted_org: todo
    - repos:
      - rocannon77/jx3-python-http-01-7
      trusted_org: todo
    welcome:
    - message_template: Welcome
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plugins
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
