apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: rocannon77
    provider: https://github.com
    providerKind: github
    repositories:
    - name: jx2-python-http-01-6
    - name: jx3-project-python-01-2
    - name: jx3-project-python-01-3
    - name: jx3-python-01-4
    - name: jx3-python-http-01-5
    scheduler: in-repo
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
